In [1]:
%cd /kaggle/working

/kaggle/working


In [2]:
import pickle
from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import polars as pl
import seaborn as sns
from hydra import compose, initialize
from omegaconf import OmegaConf

from utils.metric import score

In [3]:
def hide_submission(sub_df):
    hide_sub_df = sub_df.clone().with_columns(
        [pl.lit(0.0).alias(f"ptend_q0002_{i}") for i in range(12, 22)]
    )
    return hide_sub_df

In [4]:
base_sub_path = "gs://kaggle-leap/kami/20240610_ensemble_nelder_mead2_lb078544.parquet"
base_sub_df = pl.read_parquet(base_sub_path)
base_sub_df.head()

shape: (5, 369)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ sample_id ┆ ptend_t_0 ┆ ptend_t_1 ┆ ptend_t_2 ┆ … ┆ cam_out_S ┆ cam_out_S ┆ cam_out_S ┆ cam_out_ │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ OLS       ┆ OLL       ┆ OLSD      ┆ SOLLD    │
│ str       ┆ f64       ┆ f64       ┆ f64       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ test_0    ┆ 0.000003  ┆ -0.000065 ┆ -0.000085 ┆ … ┆ -0.033577 ┆ -0.049489 ┆ 0.09329   ┆ 0.212398 │
│ test_10   ┆ -0.000015 ┆ -0.00005  ┆ -0.000034 ┆ … ┆ -0.316943 ┆ -0.456919 ┆ 0.0302    ┆ 0.172592 │
│ test_100  ┆ -0.000007 ┆ -0.00008  ┆ -0.000033 ┆ … ┆ 0.947471  ┆ 0.65194   ┆ 0.288081  ┆ 0.205645 │
│ test_1000 ┆ 0.000026  ┆ 0.000007  ┆ 0.000033  ┆ … ┆ -2.280668 ┆ 2.305229  ┆ 1.976705  ┆ -0.31076 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 4        │
│ test_1000 ┆ 0.000048  ┆ 0.000026  ┆ 0.000045  ┆ … ┆ 446.29156 ┆ 452.6363  ┆ 48.597155 ┆ 2.662356 │
│ 0         ┆           ┆           ┆           ┆   ┆ 5         ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

## timestamp使った予測値で置き換える

In [5]:
time_sub_path = "gs://kaggle-leap/kami/experiments/610_sim6/mid/submission.parquet"
time_sub_df = pl.read_parquet(time_sub_path)
time_sub_df.tail()

shape: (5, 369)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ sample_id ┆ ptend_t_0 ┆ ptend_t_1 ┆ ptend_t_2 ┆ … ┆ cam_out_S ┆ cam_out_S ┆ cam_out_S ┆ cam_out_ │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ OLS       ┆ OLL       ┆ OLSD      ┆ SOLLD    │
│ str       ┆ f64       ┆ f64       ┆ f64       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ test_9999 ┆ -0.000004 ┆ -0.000042 ┆ -0.000038 ┆ … ┆ -0.475033 ┆ 0.748098  ┆ 0.823573  ┆ 0.397303 │
│ 4         ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ test_9999 ┆ 0.000029  ┆ -0.000017 ┆ 0.000055  ┆ … ┆ 17.049208 ┆ 23.653017 ┆ 18.294265 ┆ 9.334201 │
│ 5         ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ test_9999 ┆ 0.000055  ┆ 0.000017  ┆ 0.000052  ┆ … ┆ 132.67483 ┆ 134.04022 ┆ 90.260488 ┆ 46.92099 │
│ 6         ┆           ┆           ┆           ┆   ┆           ┆ 2         ┆           ┆ 4        │
│ test_9999 ┆ 0.000001  ┆ -0.000018 ┆ -0.000052 ┆ … ┆ -1.828611 ┆ -2.861001 ┆ -0.191153 ┆ -1.40167 │
│ 7         ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 2        │
│ test_9999 ┆ 0.000044  ┆ 0.00005   ┆ 0.000082  ┆ … ┆ 265.99140 ┆ 259.89135 ┆ 75.850059 ┆ 29.08353 │
│ 8         ┆           ┆           ┆           ┆   ┆ 5         ┆ 3         ┆           ┆ 4        │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [6]:
class_exp = "701_multi_class/small"
# class_exp = "700_binary_classify/small"

In [7]:
# 閾値ごとの値をチェック

from sklearn.metrics import precision_score, recall_score

val2_predict_df = pl.read_parquet(
    f"gs://kaggle-leap/kami/experiments/{class_exp}/val2_predict.parquet"
)
val2_label_df = pl.read_parquet(
    f"gs://kaggle-leap/kami/experiments/{class_exp}/val2_label.parquet"
)

valid_preds = val2_predict_df.select(["0"]).to_numpy()  # classの番号
valid_y_class = val2_label_df.select(["0"]).to_numpy() == 0

thresholds = [0.5, 0.7, 0.9, 0.99, 0.999, 0.99999, 0.999999]
for threshold in thresholds:
    y_pred = (valid_preds > threshold).astype(np.int64)
    # リコールと精度を計算
    num_cand = np.sum(y_pred)
    precision = precision_score(valid_y_class, y_pred)
    recall = recall_score(valid_y_class, y_pred)
    print(
        f"Threshold: {threshold:.5f}, Num:{num_cand}, Precision: {precision:.5f}, Recall: {recall:.5f}"
    )

Threshold: 0.50000, Num:165832, Precision: 0.98164, Recall: 0.99967
Threshold: 0.70000, Num:164957, Precision: 0.98662, Recall: 0.99944
Threshold: 0.90000, Num:163894, Precision: 0.99243, Recall: 0.99885
Threshold: 0.99000, Num:162458, Precision: 0.99746, Recall: 0.99511
Threshold: 0.99900, Num:159495, Precision: 0.99945, Recall: 0.97892
Threshold: 0.99999, Num:116563, Precision: 1.00000, Recall: 0.71581
Threshold: 1.00000, Num:54501, Precision: 1.00000, Recall: 0.33469


In [8]:
class_pred_df = pl.read_parquet(
    f"gs://kaggle-leap/kami/experiments/{class_exp}/test_predict.parquet"
)
class_preds = class_pred_df.get_column("0").to_numpy().reshape(-1)
class_pred_df.tail()

shape: (5, 6)
┌────────┬───────────┬───────────┬───────────┬───────────┬────────────┐
│ index  ┆ 0         ┆ 1         ┆ 2         ┆ 3         ┆ 4          │
│ ---    ┆ ---       ┆ ---       ┆ ---       ┆ ---       ┆ ---        │
│ i64    ┆ f32       ┆ f32       ┆ f32       ┆ f32       ┆ f32        │
╞════════╪═══════════╪═══════════╪═══════════╪═══════════╪════════════╡
│ 624995 ┆ 1.0       ┆ 2.0277e-7 ┆ 1.1019e-7 ┆ 2.1507e-8 ┆ 1.0022e-10 │
│ 624996 ┆ 0.000012  ┆ 0.987593  ┆ 0.012306  ┆ 0.000088  ┆ 1.8166e-7  │
│ 624997 ┆ 0.99999   ┆ 0.000005  ┆ 3.0728e-7 ┆ 0.000004  ┆ 1.1756e-9  │
│ 624998 ┆ 2.9659e-7 ┆ 0.999991  ┆ 0.000007  ┆ 9.7062e-7 ┆ 8.0808e-9  │
│ 624999 ┆ 4.3638e-7 ┆ 0.000002  ┆ 0.000559  ┆ 0.006239  ┆ 0.9932     │
└────────┴───────────┴───────────┴───────────┴───────────┴────────────┘

In [10]:
# takoi-san check
print(base_sub_df["sample_id"].to_numpy()[class_preds > 0.999])
df = pl.read_parquet("output/exp152_143.parquet")
df.sort("sample_id")

shape: (117_263, 7)
┌────────┬──────────┬──────────┬───────────┬─────────────┬─────────────────┬───────────┐
│ nears  ┆ dist     ┆ old_time ┆ new_place ┆ sample_id   ┆ time_6_18_66_78 ┆ old_place │
│ ---    ┆ ---      ┆ ---      ┆ ---       ┆ ---         ┆ ---             ┆ ---       │
│ i64    ┆ f32      ┆ i64      ┆ i64       ┆ str         ┆ i64             ┆ i64       │
╞════════╪══════════╪══════════╪═══════════╪═════════════╪═════════════════╪═══════════╡
│ 258761 ┆ 0.005093 ┆ 20190    ┆ 329       ┆ test_100008 ┆ 0               ┆ 329       │
│ 456820 ┆ 0.01054  ┆ 35670    ┆ 244       ┆ test_100016 ┆ 0               ┆ 244       │
│ 235737 ┆ 0.011838 ┆ 18390    ┆ 345       ┆ test_100023 ┆ 0               ┆ 345       │
│ 234122 ┆ 0.00494  ┆ 18270    ┆ 266       ┆ test_100027 ┆ 0               ┆ 266       │
│ 69637  ┆ 0.028217 ┆ 5430     ┆ 133       ┆ test_100028 ┆ 0               ┆ 133       │
│ …      ┆ …        ┆ …        ┆ …         ┆ …           ┆ …               ┆ …         │
│ 412236 ┆ 0.018188 ┆ 32190    ┆ 204       ┆ test_99956  ┆ 0               ┆ 204       │
│ 419900 ┆ 0.01401  ┆ 32790    ┆ 188       ┆ test_99969  ┆ 0               ┆ 188       │
│ 392107 ┆ 0.007062 ┆ 30630    ┆ 43        ┆ test_99976  ┆ 0               ┆ 43        │
│ 304618 ┆ 0.012626 ┆ 23790    ┆ 106       ┆ test_99994  ┆ 0               ┆ 106       │
│ 57576  ┆ 0.000487 ┆ 4470     ┆ 360       ┆ test_99996  ┆ 0               ┆ 360       │
└────────┴──────────┴──────────┴───────────┴─────────────┴─────────────────┴───────────┘

In [15]:
# 閾値以上の行について、カラムごとにR2を計算して一定値以上であれば置き換えを行う
from sklearn.metrics import r2_score

threshold = 0.999999
replace_index = class_preds > threshold
print(f"replace num:{replace_index.sum()} rate:{replace_index.sum()/len(class_preds)}")

replace_sub_df = base_sub_df.clone()
r2_score_vals = []

for col in base_sub_df.columns[1:]:
    time_pred = time_sub_df[col].to_numpy()
    base_pred = base_sub_df[col].to_numpy()
    r2_score_val = r2_score(
        base_pred[replace_index],
        time_pred[replace_index],
    )
    if r2_score_val > 0.2:
        replace_pred = base_sub_df[col].to_numpy().copy()
        replace_pred[replace_index] = time_pred[replace_index]
        replace_sub_df = replace_sub_df.with_columns(
            pl.Series(name=col, values=replace_pred)
        )
        r2_score_vals.append(r2_score_val)
    else:
        print(col, r2_score_val)

replace num:37579 rate:0.0601264
ptend_t_0 -1.0980285257296458
ptend_t_1 -1.0694982052031352
ptend_t_2 -1.2099677293816518
ptend_t_3 -1.1025231909900648
ptend_t_4 -0.9513752402615518
ptend_t_5 -0.840166219085563
ptend_t_6 -0.7824307275571811
ptend_t_7 -0.7738450543616655
ptend_t_8 -0.7901498511873826
ptend_t_9 -0.7876033488899126
ptend_t_10 -0.7891441445146996
ptend_t_11 -0.8281991730847809
ptend_t_12 -0.9040510896012306
ptend_t_13 -1.0112551246729726
ptend_t_14 -1.1976971246930552
ptend_t_15 -1.5649923328538753
ptend_t_16 -2.363472421630556
ptend_t_17 -4.621125880212753
ptend_t_18 -7.246321444042859
ptend_t_19 -5.721791972250844
ptend_t_20 -2.9765549727013725
ptend_t_21 -2.006911144438943
ptend_t_22 -1.7223968333020254
ptend_t_23 -1.5381211706594287
ptend_t_24 -1.5158370400677827
ptend_t_25 -1.4263914012709042
ptend_t_26 -1.3908081235900087
ptend_t_27 -1.4690782053438847
ptend_t_28 -1.6096503549664938
ptend_t_29 -1.8263072611737008
ptend_t_30 -2.0739651948983515
ptend_t_31 -2.32158388

In [57]:
base_pred[replace_index] = 1

ValueError: assignment destination is read-only

In [16]:
time_pred[304:]

array([ 2.11722729e-05, -1.87040935e-05, -6.29029656e-06, ...,
        5.51110531e-05,  1.06978151e-06,  4.36059185e-05])

In [17]:
base_pred[304:]

array([ 3.94424593e-05,  3.97818179e-05,  4.17194799e-05, ...,
        3.05507264e-05, -1.91269003e-05,  3.53775701e-05])

In [20]:
path = "input/sim6_data/test/id384.npz"
a = np.load(path)

In [23]:
a["x"]

array([[2.08036108e+02, 2.27158595e+02, 2.30732909e+02, ...,
        4.90858386e-07, 4.90858386e-07, 4.90858386e-07],
       [2.13779131e+02, 2.22641431e+02, 2.34139642e+02, ...,
        4.90858386e-07, 4.90858386e-07, 4.90858386e-07],
       [2.20849426e+02, 2.22368835e+02, 2.36797136e+02, ...,
        4.90858386e-07, 4.90858386e-07, 4.90858386e-07],
       ...,
       [2.11430493e+02, 2.36875820e+02, 2.53411973e+02, ...,
        4.90858386e-07, 4.90858386e-07, 4.90858386e-07],
       [2.37398034e+02, 2.25109263e+02, 2.36295219e+02, ...,
        4.90858386e-07, 4.90858386e-07, 4.90858386e-07],
       [2.14821313e+02, 2.31346606e+02, 2.38470580e+02, ...,
        4.90858386e-07, 4.90858386e-07, 4.90858386e-07]])

In [24]:
test_df = pl.read_csv("input/leap-atmospheric-physics-ai-climsim/test.csv", n_rows=500)

In [25]:
test_df[384:]

shape: (116, 557)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ sample_id ┆ state_t_0 ┆ state_t_1 ┆ state_t_2 ┆ … ┆ pbuf_N2O_ ┆ pbuf_N2O_ ┆ pbuf_N2O_ ┆ pbuf_N2O │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ 56        ┆ 57        ┆ 58        ┆ _59      │
│ str       ┆ f64       ┆ f64       ┆ f64       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ test_1004 ┆ 208.03610 ┆ 227.15859 ┆ 230.73290 ┆ … ┆ 4.9086e-7 ┆ 4.9086e-7 ┆ 4.9086e-7 ┆ 4.9086e- │
│ 55        ┆ 8         ┆ 5         ┆ 9         ┆   ┆           ┆           ┆           ┆ 7        │
│ test_1004 ┆ 213.77913 ┆ 222.64143 ┆ 234.13964 ┆ … ┆ 4.9086e-7 ┆ 4.9086e-7 ┆ 4.9086e-7 ┆ 4.9086e- │
│ 56        ┆ 1         ┆ 1         ┆ 2         ┆   ┆           ┆           ┆           ┆ 7        │
│ test_1004 ┆ 220.84942 ┆ 222.36883 ┆ 236.79713 ┆ … ┆ 4.9086e-7 ┆ 4.9086e-7 ┆ 4.9086e-7 ┆ 4.9086e- │
│ 58        ┆ 6         ┆ 5         ┆ 6         ┆   ┆           ┆           ┆           ┆ 7        │
│ test_1004 ┆ 210.30384 ┆ 217.96313 ┆ 230.29439 ┆ … ┆ 4.9086e-7 ┆ 4.9086e-7 ┆ 4.9086e-7 ┆ 4.9086e- │
│ 59        ┆ 4         ┆ 3         ┆ 3         ┆   ┆           ┆           ┆           ┆ 7        │
│ test_1004 ┆ 209.32250 ┆ 231.10362 ┆ 241.32514 ┆ … ┆ 4.9086e-7 ┆ 4.9086e-7 ┆ 4.9086e-7 ┆ 4.9086e- │
│ 6         ┆ 7         ┆           ┆ 2         ┆   ┆           ┆           ┆           ┆ 7        │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ test_1005 ┆ 210.89629 ┆ 226.94952 ┆ 246.32834 ┆ … ┆ 4.9086e-7 ┆ 4.9086e-7 ┆ 4.9086e-7 ┆ 4.9086e- │
│ 83        ┆ 9         ┆ 4         ┆ 1         ┆   ┆           ┆           ┆           ┆ 7        │
│ test_1005 ┆ 219.24230 ┆ 213.68380 ┆ 231.43643 ┆ … ┆ 4.9086e-7 ┆ 4.9086e-7 ┆ 4.9086e-7 ┆ 4.9086e- │
│ 85        ┆ 8         ┆ 7         ┆           ┆   ┆           ┆           ┆           ┆ 7        │
│ test_1005 ┆ 188.64103 ┆ 218.68258 ┆ 251.38984 ┆ … ┆ 4.9086e-7 ┆ 4.9086e-7 ┆ 4.9086e-7 ┆ 4.9086e- │
│ 87        ┆ 3         ┆ 6         ┆           ┆   ┆           ┆           ┆           ┆ 7        │
│ test_1005 ┆ 209.36836 ┆ 216.82647 ┆ 229.87104 ┆ … ┆ 4.9086e-7 ┆ 4.9086e-7 ┆ 4.9086e-7 ┆ 4.9086e- │
│ 88        ┆ 5         ┆ 5         ┆ 2         ┆   ┆           ┆           ┆           ┆ 7        │
│ test_1005 ┆ 220.35647 ┆ 231.26710 ┆ 242.05276 ┆ … ┆ 4.9086e-7 ┆ 4.9086e-7 ┆ 4.9086e-7 ┆ 4.9086e- │
│ 89        ┆ 1         ┆ 7         ┆ 4         ┆   ┆           ┆           ┆           ┆ 7        │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘