In [14]:
%cd /kaggle/working

import numpy as np

y_rms_sub = np.load("output/preprocess/normalize_006_air/bolton/y_rms_sub.npy")

/kaggle/working


In [15]:
y_rms_sub[60:120]

array([2.06439929e-14, 1.82666423e-14, 1.37008071e-14, 5.36429003e-15,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       1.14740943e-12, 9.23171947e-13, 6.80111288e-12, 2.81246110e-11,
       2.84467740e-11, 2.16983889e-11, 4.05033655e-11, 8.81579447e-11,
       1.85301001e-10, 4.08271061e-10, 8.83215940e-10, 1.72548298e-09,
       3.02829093e-09, 4.81663224e-09, 6.91657165e-09, 9.09642579e-09,
       1.12731174e-08, 1.35465045e-08, 1.57193179e-08, 1.74671680e-08,
       1.88764454e-08, 2.01397004e-08, 2.14845952e-08, 2.31655174e-08,
       2.51734595e-08, 2.75351783e-08, 3.02503091e-08, 3.34794253e-08,
       3.70612117e-08, 4.09563532e-08, 4.48960936e-08, 4.86536866e-08,
       5.20393141e-08, 5.50427548e-08, 5.71367961e-08, 5.82413235e-08,
       5.88049087e-08, 5.88288029e-08, 5.85380982e-08, 5.80450981e-08,
       5.73203074e-08, 5.63145337e-08, 5.45075163e-08, 5.15448650e-08,
      

In [3]:
y_rms_sub[120:180]

array([0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       2.19884010e-40, 1.03234335e-45, 8.40514244e-51, 2.07709300e-51,
       7.50849372e-48, 5.34474007e-43, 3.62491349e-40, 9.26447481e-38,
       6.80187613e-35, 5.21781739e-32, 4.38805167e-29, 3.17520802e-26,
       6.61272272e-23, 2.04547205e-18, 2.72195502e-13, 2.69247429e-12,
       7.03276211e-11, 3.33126443e-10, 6.97950355e-10, 1.13045464e-09,
       1.78530619e-09, 2.59032068e-09, 3.48029620e-09, 4.49027179e-09,
       5.52274894e-09, 6.46743216e-09, 7.24145554e-09, 7.89853010e-09,
       8.47688616e-09, 9.00853668e-09, 9.50688668e-09, 9.98321442e-09,
       1.04636822e-08, 1.09340478e-08, 1.12521867e-08, 1.12574833e-08,
       1.09411443e-08, 1.03535599e-08, 9.56867319e-09, 8.62849057e-09,
       7.57921946e-09, 6.47278712e-09, 5.46006725e-09, 4.64789014e-09,
      

In [30]:
import pickle

with open("output/preprocess/standard_scale/base/scaler.pkl", "rb") as f:
    scaler = pickle.load(f)

/opt/conda/lib/python3.10/site-packages/sklearn/base.py:376: InconsistentVersionWarning: Trying to unpickle estimator StandardScaler from version 1.4.2 when using version 1.5.0. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations
  warnings.warn(


In [32]:
scaler.scale_[120:180]

array([1.00000000e+00, 1.00000000e+00, 1.00000000e+00, 1.00000000e+00,
       1.00000000e+00, 1.00000000e+00, 1.00000000e+00, 1.00000000e+00,
       1.00000000e+00, 1.00000000e+00, 1.00000000e+00, 1.00000000e+00,
       2.19884010e-40, 1.03234335e-45, 8.40514244e-51, 2.07709300e-51,
       7.50849372e-48, 5.34474007e-43, 3.62491349e-40, 9.26447481e-38,
       6.80187613e-35, 5.21781739e-32, 4.38805167e-29, 3.17520802e-26,
       6.61272272e-23, 2.04547205e-18, 2.72195502e-13, 2.69247429e-12,
       7.03276211e-11, 3.33126443e-10, 6.97950355e-10, 1.13045464e-09,
       1.78530619e-09, 2.59032068e-09, 3.48029620e-09, 4.49027179e-09,
       5.52274894e-09, 6.46743216e-09, 7.24145554e-09, 7.89853010e-09,
       8.47688616e-09, 9.00853668e-09, 9.50688668e-09, 9.98321442e-09,
       1.04636822e-08, 1.09340478e-08, 1.12521867e-08, 1.12574833e-08,
       1.09411443e-08, 1.03535599e-08, 9.56867319e-09, 8.62849057e-09,
       7.57921946e-09, 6.47278712e-09, 5.46006725e-09, 4.64789014e-09,
      

In [34]:
y_rms_sub[120:180]

array([0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       2.19884010e-40, 1.03234335e-45, 8.40514244e-51, 2.07709300e-51,
       7.50849372e-48, 5.34474007e-43, 3.62491349e-40, 9.26447481e-38,
       6.80187613e-35, 5.21781739e-32, 4.38805167e-29, 3.17520802e-26,
       6.61272272e-23, 2.04547205e-18, 2.72195502e-13, 2.69247429e-12,
       7.03276211e-11, 3.33126443e-10, 6.97950355e-10, 1.13045464e-09,
       1.78530619e-09, 2.59032068e-09, 3.48029620e-09, 4.49027179e-09,
       5.52274894e-09, 6.46743216e-09, 7.24145554e-09, 7.89853010e-09,
       8.47688616e-09, 9.00853668e-09, 9.50688668e-09, 9.98321442e-09,
       1.04636822e-08, 1.09340478e-08, 1.12521867e-08, 1.12574833e-08,
       1.09411443e-08, 1.03535599e-08, 9.56867319e-09, 8.62849057e-09,
       7.57921946e-09, 6.47278712e-09, 5.46006725e-09, 4.64789014e-09,
      

In [23]:
import polars as pl

df = pl.read_parquet("input/train.parquet", n_rows=600000)

In [24]:
df[:, 557 + 150].mean()

-7.599625927248888e-11

In [25]:
a = df[:, 557 + 150].to_numpy()
a[a.nonzero()].mean()

-1.1290122281879043e-10

In [26]:
from sklearn.preprocessing import StandardScaler

In [27]:
a = df[:, 557 + 60 : 557 + 120].to_numpy()
scaler = StandardScaler()
scaler.fit(a)

StandardScaler()

In [29]:
scaler.scale_

array([3.15511643e-14, 2.83037479e-14, 2.38121871e-14, 1.06644371e-14,
       1.00000000e+00, 1.00000000e+00, 1.00000000e+00, 1.00000000e+00,
       1.00000000e+00, 1.00000000e+00, 1.00000000e+00, 1.00000000e+00,
       6.69345897e-14, 2.49323451e-13, 4.51128202e-12, 3.45381720e-11,
       3.66104368e-11, 1.96715684e-11, 3.99572202e-11, 8.53717093e-11,
       1.71065005e-10, 3.71979451e-10, 8.19342828e-10, 1.60929904e-09,
       2.84745777e-09, 4.58496440e-09, 6.64700756e-09, 8.83686599e-09,
       1.10562334e-08, 1.33756220e-08, 1.55799489e-08, 1.74578804e-08,
       1.89265934e-08, 2.03438700e-08, 2.17572381e-08, 2.35212322e-08,
       2.58035012e-08, 2.85705309e-08, 3.15583993e-08, 3.51396097e-08,
       3.92372175e-08, 4.34183298e-08, 4.76172785e-08, 5.14300539e-08,
       5.47590042e-08, 5.75660711e-08, 5.98093284e-08, 6.08715171e-08,
       6.12709048e-08, 6.09779182e-08, 6.06071395e-08, 5.99447992e-08,
       5.89109060e-08, 5.73449924e-08, 5.52430941e-08, 5.21615526e-08,
      

In [22]:
2.84467740e-11, 2.16983889e-11, 4.05033655e-11, 8.81579447e-11

2.220446049250313e-16